#!/bin/bash

source "$HOME/.config/omacase/current/theme/borders"

options=(
    style=square
    active_color="$ACTIVE_COLOR"
    inactive_color="$INACTIVE_COLOR"
    width=6.0
    hidpi=on
    blacklist="iPhone Mirroring"
)

borders "${options[@]}"
