#+author: Matthew Dong
#+date: <2025-07-27 Sun>
#+title: Instructions for my personal dotfiles

* Prerequisites
⚠️ WARNING!
Only MacOS Sequoia is tested. Not sure about how this would behave on a beta or an older system.
However, some components of this config (e.g. nvim) will work on any system.
- You pretty much don't need anything except curl.

* Install Instructions
#+BEGIN_SRC sh

curl -fsSL https://raw.githubusercontent.com/matt-dong-123/dotfiles/refs/heads/main/install.sh
chmod +x install.sh
./install.sh

#+END_SRC
Paste this into your terminal, and follow the steps of the install script.

* Post-install
** Vimium C
1. Install the [[https://addons.mozilla.org/en-US/firefox/addon/vimium-c/][Vimium C]] browser extension
2. In the preferences for the extension, click "Import Settings"
3. Choose the file from the path "~/.config/vimium-c/config.json"
** Firefox
1. Set vertical tabs
2. Install the following addons:
    - Brave Search: Private Search Engine
    - mtab
    - Vimium C
    - Dark Reader
    - Return YouTube Dislike
    - DeArrow
    - SponsorBlock
    - Zen Internet
    - Stylus
3. Disable 'hide filter chips' on youtube
4. Go to Zen Internet's Advanced settings and turn on the toggle for "Disable Transparency"
5. Find and install tokyo night themes for GitHub and Brave Search as well as installing "Desmos Dark Theme" by spidunno via Stylus
6. Copy the user.js in ~/.config/firefox to your profile directory
7. Delete the user.js after starting the browser (settings will be remembered automatically)
*** Option 1: Textfox
1. Install the Tokyo Night theme by Milav
2. Go to [[https://github.com/adriankarlen/textfox][the textfox repo]] and follow its instructions
3. Use the provided config.css in ~/.config/firefox/chrome and symlink it to your chrome directory
*** Option 2: Natsumi Browser
1. Download and run the [[https://github.com/greeeen-dev/natsumi-browser/releases/latest][latest natsumi installer]]

⚠️ WARNING!
Right now, only its latest RC version has an installer.
However, you can still download the stable version from the installer.
** LeaderKey
1. Go to the LeaderKey settings and go to the "Advanced" tab
2. Set the config directory to your ~/.config/leaderkey directory
3. Go back to "General" and set the shortcut to be "f13" by tapping the right command key
** Optional: Emacs
#+BEGIN_SRC sh
brew tap d12frosted/emacs-plus
brew install --cask emacs-plus
brew install --cask font-symbols-only-nerd-font
brew install cmake
#+END_SRC
- Install doom emacs
- Next, either:
#+BEGIN_SRC sh
rm -rf ~/.emacs.d
#+END_SRC
- Or backup your existing config.
