#+author: Matthew Dong
#+date: <2025-07-27 Sun>
#+title: Instructions for my personal dotfiles

* Prerequisites
⚠️ WARNING!
Only MacOS Sequoia is tested. Not sure about how this would behave on a beta or an older system.
However, some components of this config (e.g. nvim) will work on any system.
- You pretty much don't need anything except curl.

* Install Instructions
#+BEGIN_SRC sh

curl -fsSL https://raw.githubusercontent.com/matt-dong-123/dotfiles/refs/heads/main/install.sh
chmod +x install.sh
./install.sh

#+END_SRC
Paste this into your terminal, and follow the steps of the install script.

* Post-install
** Vimium C
1. Install the [[https://addons.mozilla.org/en-US/firefox/addon/vimium-c/][Vimium C]] browser extension
2. In the preferences for the extension, click "Import Settings"
3. Choose the file from the path "~/.config/vimium-c/config.json"
** Zen
1. Install the following addons:
   - Brave Search: Private Search Engine
   - Vimium C
   - Dark Reader
   - Return YouTube Dislike
   - DeArrow
   - SponsorBlock
   - Zen Internet
   - Stylus
2. Disable 'hide filter chips' on youtube
3. Go to Zen Internet's Advanced settings and turn on the toggle for "Disable Transparency"
4. Find and install tokyo night themes for GitHub, Reddit, ChatGPT, and Brave Search by JoshuaMarkle as well as installing "Desmos Dark Theme" by spidunno via Stylus
5. Copy the user.js in ~/.config/zen to your profile directory
6. Delete the user.js after starting the browser (settings will be remembered automatically)
6. Install [[https://github.com/CosmoCreeper/Sine][Sine mods]]
7. Install Nebula
8. Disable loading animation in Nebula settings
** LeaderKey
1. Go to the LeaderKey settings and go to the "Advanced" tab
2. Set the config directory to your ~/.config/leaderkey directory
3. Go back to "General" and set the shortcut to be "f13" by tapping the right command key
** Optional: Emacs
#+BEGIN_SRC sh
brew tap d12frosted/emacs-plus
brew install --cask emacs-plus --with-modern-black-dragon-icon
brew install --cask font-symbols-only-nerd-font
brew install cmake
#+END_SRC
- Install doom emacs
- Next, either:
#+BEGIN_SRC sh
rm -rf ~/.emacs.d
#+END_SRC
- Or backup your existing config.
