# Start sketchybar with aerospace
after-startup-command = [
    'exec-and-forget brew services restart sketchybar',
    'exec-and-forget brew services restart borders',
]

# Send signal to change workspace to sketchybar
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Options
start-at-login = true
accordion-padding = 0
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'

# App Rules:
on-window-detected = [
    { if.app-id = "app.zen-browser.zen", run = "move-node-to-workspace browser" },
    { if.app-id = "com.github.wez.wezterm", run = "move-node-to-workspace coding" },
    { if.app-id = "org.musescore.MuseScore", run = "move-node-to-workspace music" },
    { if.app-id = "com.steinberg.dorico5", run = "move-node-to-workspace music" },
    { if.app-id = "com.tencent.xinWeChat", run = "move-node-to-workspace social" },
    { if.app-id = "us.zoom.xos", run = "move-node-to-workspace work" },
    { if.app-id = "com.kingsoft.wpsoffice.mac", run = "move-node-to-workspace work" },
    { if.app-id = "com.apple.finder", run = "layout floating" },
    { if.app-name-regex-substring = "alacritty", run = 'layout floating' },
]

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 3
outer.bottom = 3
outer.top = 3
outer.right = 3

# Keys
[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
shift-alt-h = 'move left'
shift-alt-j = 'move down'
shift-alt-k = 'move up'
shift-alt-l = 'move right'
ctrl-alt-enter = 'fullscreen'                      # Unlike the others because bad habits
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

cmd-shift-space = 'mode workspace'
alt-shift-semicolon = 'mode service'

[mode.workspace.binding]
esc = ['mode main']
b = ['workspace browser', 'mode main']
c = ['workspace coding', 'mode main']
m = ['workspace music', 'mode main']
s = ['workspace social', 'mode main']
w = ['workspace work', 'mode main']
shift-b = ['move-node-to-workspace browser', 'workspace browser', 'mode main']
shift-c = ['move-node-to-workspace coding', 'workspace coding', 'mode main']
shift-m = ['move-node-to-workspace music', 'workspace music', 'mode main']
shift-s = ['move-node-to-workspace social', 'workspace social', 'mode main']
shift-w = ['move-node-to-workspace work', 'workspace work', 'mode main']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
