notARepository: skip
gui:
  skipNoStagedFilesWarning: false
  showRandomTip: false
  commit:
    signOff: false
  editor: "nvim"
  nerdFontsVersion: "3" 
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - blue
    optionsTextColor:
      - white
