#!/bin/bash

options=(
    style=square
    active_color="gradient(top_left=0xffcc241d,bottom_right=0xfffabd2f)"
    inactive_color="0xff888888"
    width=6.0
    hidpi=on
    blacklist="iPhone Mirroring"
)

borders "${options[@]}"
