#!/bin/bash

options=(
    style=square
    active_color="gradient(top_left=0xff8be9fd,bottom_right=0xffbd93f9)"
    inactive_color="0xff888888"
    width=6.0
    hidpi=on
    blacklist="iPhone Mirroring"
)

borders "${options[@]}"
