#!/bin/bash

options=(
    active_color="gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)"
    inactive_color="0xff888888"
    width=6.0
    hidpi=on
    blacklist="iPhone Mirroring"
)

borders "${options[@]}"
