return {
    'mrjones2014/smart-splits.nvim',
    opts = {},
    keys = {
        {
            '<M-h>',
            function()
                require('smart-splits').resize_left()
            end,
        },
        {
            '<M-j>',
            function()
                require('smart-splits').resize_down()
            end,
        },
        {
            '<M-k>',
            function()
                require('smart-splits').resize_up()
            end,
        },
        {
            '<M-l>',
            function()
                require('smart-splits').resize_right()
            end,
        },
        {
            '<C-h>',
            function()
                require('smart-splits').move_cursor_left()
            end,
        },
        {
            '<C-j>',
            function()
                require('smart-splits').move_cursor_down()
            end,
        },
        {
            '<C-k>',
            function()
                require('smart-splits').move_cursor_up()
            end,
        },
        {
            '<C-l>',
            function()
                require('smart-splits').move_cursor_right()
            end,
        },
    },
}
