general.import = ["~/.config/omacase/current/theme/alacritty.toml"]

[window]
dimensions = { columns = 125, lines = 30 }
position = { x = 300, y = 500 }
decorations = "none"
opacity = 0.75
blur = true

[font]
normal = { family = "Maple Mono NF CN" }
size = 20
